### ISSUE TITLE
instructions for manual filtering of files

### ISSUE THREAD

**Issue by santiyounger** [roam-garden/roam-export#1]
This looks amazing, it's exactly what I need to be able to filter pages
 to make them plugin.
edit:  to make them public. (accidental typo)

I saw you mentioning this in the gatsby digital garden issues

https://github.com/mathieudutour/gatsby-digital-garden/issues/31

Would you mind elaborating a bit on the README on how to use this for the purposes of manually filtering files

Thanks a lot

**Comment by Stvad** [comment]
Hey @santiyounger atm it's mainly a library, though I recently pushed out a basic CLI support:

```
npx roam-export -h

USAGE
  $ roam-export INPUTFILE [OUTPUTFILE]

OPTIONS
  -f, --filter=filter  Filter json
  -h, --help           show CLI help
  -v, --version        show CLI version
```

Where filter is a JSON string that matches the following type: https://github.com/roam-garden/roam-export/blob/master/src/filtering.ts#L15

I'll try to update Readme to have more details soonish. I'd be also happy to accept contributions  😉 

---

>make them plugin.

did you mean "make them public"/or which plugin are you building?

---

Also to check in have you seen https://roam.garden/ ? 🙂

**Comment by santiyounger** [comment]
Hey thanks for the reply. 

> did you mean "make them public"/or which plugin are you building?

Apologies autocorrect messed that up. I meant to make the public.

Thanks for the info I will be trying out CLI support, thanks for that tip!

Appreciate your help, keep up the great work
